//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mirabeau.DatabaseReleaseTool.Configuration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mirabeau.DatabaseReleaseTool.Configuration.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Misc.
        /// </summary>
        public static string DirectoryIgnoreListStructureTemplate {
            get {
                return ResourceManager.GetString("DirectoryIgnoreListStructureTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0. PreDataScripts
        ///1. DatabaseCreate
        ///2. Tables
        ///3. Triggers
        ///4. Functions
        ///5. StoredProcedures
        ///6. Indexes
        ///7. Views
        ///999. PostDataScripts
        ///Version.
        /// </summary>
        public static string DirectoryStructureTemplate {
            get {
                return ResourceManager.GetString("DirectoryStructureTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseReleaseTool by Dorus Verhoeckx, Mirabeau BV (c) 2009
        ///Updates a database with the given scripts directory.
        ///
        ///Usage:
        ///To update a database:
        ///Mirabeau.DatabaseReleaseTool.exe -d:[pathToDatabaseScripts] -c:[configurationfile] -vf:[fromdatabaseversion] -vt:[todatabaseversion]
        ///Mirabeau.DatabaseReleaseTool.exe -d:[pathToDatabaseScripts] -server:[databaseservername] -username:[databaseusername] -password:[databasepassword] -databasename:[databasename] (-databasetype:[Oracle||MsSql||MySql] optional)-vf:[f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UsageTemplate {
            get {
                return ResourceManager.GetString("UsageTemplate", resourceCulture);
            }
        }
    }
}
